version: '3.6'

services:
  backend:
    image: node:20.10.0
    working_dir: /app
    volumes: 
      - ./backend:/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      TZ: 'Europe/Paris'
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    image: node:20.10.0
    working_dir: /code
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/code
      - /code/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  db-data: